package it.polimi.ingsw.ligtModelNotification;

public enum NotificationType {
 DECKLISTNOTIFY,
GAMEBOARDDECKLISTNOTIFY,
LEADERLISTNOTIFY, STORAGENOTIFY, STRONGBOXNOTIFY, RESERVENOTIFY, MARKETNOTIFY, EXTRAMARKETNOTIFY, ACTIVATELEADERLISTNOTIFY, FAITHNOTIFY,
}
