package it.polimi.ingsw.client.ligtModelNotification;

public enum NotificationType {
    DECKLISTNOTIFY,
    GAMEBOARDDECKLISTNOTIFY,
    LEADERLISTNOTIFY,
    STORAGENOTIFY,
    STRONGBOXNOTIFY,
    RESERVENOTIFY,
    MARKETNOTIFY,
    EXTRAMARKETNOTIFY,
    FAITHNOTIFY,
    INITLEADER,
    ACTIVATELEADER,
    DISCARDLEADER
}
