package it.polimi.ingsw.Client.View.LigtModelNotification;

public enum NotificationType {
 DECKLISTNOTIFY,
GAMEBOARDDECKLISTNOTIFY,
LEADERLISTNOTIFY, STORAGENOTIFY, STRONGBOXNOTIFY, RESERVENOTIFY, MARKETNOTIFY, EXTRAMARKETNOTIFY, ACTIVATELEADERLISTNOTIFY, FAITHNOTIFY,
}
